spring:
  main.show_banner: false
  rabbit:
    host: rabbit
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery_1:8080/eureka/,http://discovery_2:8080/eureka/
    healthcheck.enabled: true
