spring:
  main.show_banner: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery_1:8080/eureka/,http://discovery_2:8080/eureka/
    healthcheck.enabled: true
logging:
  level:
    com.netflix.discovery: 'ERROR'
